### ISSUE TITLE
trace-sample throws exception on start

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#780]
Getting this exception on trace-sample app start. The app works fine, but would be good to fix.

```
2018-06-25 13:18:59.938  WARN [-,,,] 132278 --- [-worker-ELG-2-2] i.g.n.s.i.n.u.concurrent.DefaultPromise  : An exception was thrown by io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$Sink$1.operationComplete()

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@77902202[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@bfdb2c6[Wrapped task = io.grpc.internal.SerializingExecutor@6fa3c318]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3842335e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:328)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:555)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:644)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:594)
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:418)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:372)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:415)
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:418)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:372)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:415)
	at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:392)
	at io.grpc.internal.AbstractClientStream$TransportState.access$300(AbstractClientStream.java:200)
	at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:376)
	at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:245)
	at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:178)
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:379)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:149)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:137)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1316)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1031)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.write(AbstractChannel.java:295)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:186)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.flush(WriteQueue.java:124)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dmitry-s** [comment]
that was fixed

**Comment by ChengyuanZhao** [comment]
This went away if I disabled the STACKDRIVER log appender.

now to just find out why...

**Comment by cosminstefanxp** [comment]
Up! I'm still getting the same issue, on my own app when both the trace and STACKDRIVER appender are active.

**Comment by elefeint** [comment]
Might be related to #1096. @meltsufin traced it to a hanging gRPC call.

**Comment by meltsufin** [comment]
We're told it's harmless, but I'm trying to track down the root cause.
See: https://github.com/googleapis/google-cloud-java/issues/3788

**Comment by meltsufin** [comment]
@ejona86 Have you seen this kind of error before? Any clues?

**Comment by ejona86** [comment]
An Executor is being shut down before the channel is terminated. Since gRPC doesn't use a ScheduledExecutorService for issuing RPC callbacks, this probably means someone passed in such an executor to `ManagedChannelBuilder.executor()` or `CallOptions/AbstractStub.withExecutor()`. For example, in [StackdriverTraceAutoConfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/371616e33e7ba083e722c8d7bcad2fd285f157f3/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L118).

I'd double-check the lifetime of that executor to make sure it isn't shut down before the RPCs complete.

**Comment by samhalpa** [comment]
Is this still exists in 1.1.0.RELEASE

**Comment by meltsufin** [comment]
@dmitry-s Can you please check?
