### ISSUE TITLE
v1.0.0.RELEASE samples are referring to SNAPSHOT parents

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#991]
See https://github.com/spring-cloud/spring-cloud-gcp/blob/v1.0.0.RELEASE/spring-cloud-gcp-samples/pom.xml and also the samples in that directory.

They are referring to snapshot parents, where it should be the release version.
```
	<parent>
		<artifactId>spring-cloud-gcp</artifactId>
		<groupId>org.springframework.cloud</groupId>
		<version>1.0.0.BUILD-SNAPSHOT</version>
	</parent>
```

**Comment by saturnism** [comment]
@meltsufin i updated the branch and tested it out. looks good :)

**Comment by meltsufin** [comment]
@saturnism It looks like you missed 2. Take a look here: 3232934183c94eadd0c35b7d56b58ba4fa6e7c35.

**Comment by saturnism** [comment]
good catch!

**Comment by meltsufin** [comment]
`v1.0.0.RELEASE` has been amended. Closing.
